import { Place, Itinerary } from "@/types/place";
export const FEATURED_PLACES: Place[] =[
    {
        id: '1',
        name: 'Dinh Độc Lập',
        slug: 'dinh-doc-lap',
        image: 'https://images.unsplash.com/photo-1592114714621-ccc6cacad26b?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        district: 'Quận 1',
        ward: 'Phường Bến Thành',
        rating: 4.8,
        description: 'Biểu tượng lịch sử nổi tiếng tại trung tâm Thành phố Hồ Chí Minh.',
        lat: 10.7769942,
        lng: 106.6927272,
    },
    {
        id: '2',
        name: 'Bưu điện Trung tâm Sài Gòn',
        slug: 'buu-dien-trung-tam-sai-gon',
        image: 'https://vov2.vov.vn/sites/default/files/styles/medium/public/2023-06/buu-dien-thanh-pho-hcm.jpg',
        district: 'Quận 1',
        ward: 'Phường Bến Nghé',
        rating: 4.7,
        description: 'Kiến trúc Phục Hưng Pháp tráng lệ được xây dựng từ cuối thế kỷ 19.',
        lat: 10.7798889,
        lng: 106.6980772,
    },
    {
        id: '4',
        name: 'Chợ Bến Thành',
        slug: 'cho-ben-thanh',
        image: 'https://images.unsplash.com/photo-1680783307371-749c26e0f5c3?q=80&w=800&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        district: 'Quận 1',
        ward: 'Phường Bến Thành',
        rating: 4.6,
        description: 'Địa điểm mua sắm, ẩm thực mang tính biểu tượng của thành phố.',
        lat: 10.7725168,
        lng: 106.6954459,
    },
    {
        id: '3',
        name: 'Bảo tàng Chứng tích Chiến tranh',
        slug: 'bao-tang-chung-tich-chien-tranh',
        image: 'https://ik.imagekit.io/tvlk/blog/2023/04/bao-tang-chung-tich-chien-tranh-1.jpg?tr=q-70,c-at_max,w-800,h-300,dpr-2',
        district: 'Quận 3',
        ward: 'Phường Võ Thị Sáu',
        rating: 4.9,
        description: 'Nơi lưu giữ các tư liệu, hiện vật lịch sử chiến tranh tại Việt Nam.',
        lat: 10.7795106,
        lng: 106.6895167,
    },
];
export const SAMPLE_ITINERARIES: Itinerary[] = [
    {
        id: 'tour-di-san-1-ngay',
        title: 'Hành Trình Di Sản Văn Hóa & Lịch Sử',
        duration: '4 giờ',
        distance: '6.2 km',
        stopsCount: 3,
        description: 'Khám phá các công trình biểu tượng khu vực trung tâm Quận 1 và Quận 3.',
        highlights: ['Bưu điện TP', 'Dinh Độc Lập', 'Bảo tàng Chứng tích Chiến tranh'],
    },
    {
        id: 'food-tour-cho-lon',
        title: 'Khám Phá Hương Vị Ẩm Thực Chợ Lớn',
        duration: '3.5 giờ',
        distance: '4.8 km',
        stopsCount: 4,
        description: 'Trải nghiệm ẩm thực người Hoa và các khu phố cổ kính tại Quận 5.',
        highlights: ['Hội quán Hà Chương', 'Chợ Bình Tây', 'Phố sủi cảo Hà Tôn Quyền'],
    },
];
